### PR TITLE
[AESH-500] Provide API to look at character at a specific position in a line

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/AESH-500

### CODE REVIEW

**Comment by stalep** [comment]
i can merge this if you need it, but if you need to match open/close characters, have you tried to use the org.aesh.parser.LineParser? we us it for all the line parsing in æsh, it works very well.

**Comment by stalep** [comment]
im merging this anyway. if its useful for you it might be useful for others as well :)

**Comment by iweiss** [comment]
> i can merge this if you need it, but if you need to match open/close characters, have you tried to use the org.aesh.parser.LineParser? we us it for all the line parsing in æsh, it works very well.

I did not know about it but looking at it I see I'll be sending another patch soon ;)

**Comment by stalep** [comment]
sounds like a plan! :)

**Pull request merged**
